name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Install Dependencies
      run: ./mvnw dependency:resolve

  validations:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install & Compile
      run: ./mvnw install -DskipTests
    
    - name: Validate & Checkstyle
      run: ./mvnw validate

    - name: Run Tests
      run: ./mvnw verify

    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "target/surefire-reports/**/TEST-*.xml"
      if: always()

    - name: Coverage Summary
      run: |
        missed=$(cat target/jacoco-report/jacoco.xml | grep -oP '<counter type="LINE" missed="\K\d+' | tail -1)
        covered=$(cat target/jacoco-report/jacoco.xml | grep -oP '<counter type="LINE" missed="\d+" covered="\K\d+' | tail -1)
        total=$(( $missed + $covered ))
        percentage=$((($covered * 100) / $total))
        echo "📊 Coverage: ${percentage}% >> $GITHUB_STEP_SUMMARY