name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Install Dependencies
      run: ./mvnw dependency:resolve

  validations:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install
      run: ./mvnw install -DskipTests
    
    - name: Validate
      run: ./mvnw validate

    - name: Tests
      run: ./mvnw verify

    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "target/surefire-reports/**/TEST-*.xml"
      if: always()
